name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: windows-latest
    env:
      SERVICE_ACCOUNT_KEY: s{{ secrets.SERVIVE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip install virtualenv
          virtualenv venv
          venv\Scripts\activate
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip install -r requirements_test.text
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py
          


